[project]
name = "project-cloud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.54",
    "requests>=2.32.5",
    "python-dotenv>=1.0.0",
    "dotenv>=0.9.9",
]
